version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: visioscience-backend:1.0
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    build:
      context: ./frontend
    image: visioscience-frontend:1.0
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  visioscience-network:
    driver: overlay
