apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          env:
            # Adresa de host a serviciului MongoDB
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongodb-service"
            # Portul pe care ascultă MongoDB
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            # Nume utilizator root (din MONGO_INITDB_ROOT_USERNAME)
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            # Parola root (din MONGO_INITDB_ROOT_PASSWORD)
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "root"
            # Opțional, user + pass pentru acces la interfața mongo-express
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "password"
            - name: ME_CONFIG_SITE_BASEURL
              value: "/mongo-express"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  type: ClusterIP
  selector:
    app: mongo-express
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /mongo-express
            pathType: Prefix
            backend:
              service:
                name: mongo-express-service
                port:
                  number: 8081
