apiVersion: v1
kind: Service
metadata:
  name: mongo-feed-data-service
spec:
  selector:
    app: mongo-feed-data-service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
