/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import islandScene from "../assets/3d/correct_Populated_islands.glb";

const Island = (props) => {
  const islandRef = useRef();
  const { nodes, materials } = useGLTF(islandScene);

  return (
    <a.group ref={islandRef} {...props}>
      <mesh
        geometry={nodes.Object_41.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_47.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_59.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_60.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_84.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_85.geometry} material={materials.Madeira} />
      <mesh
        geometry={nodes.Object_87.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_88.geometry} material={materials.Madeira} />
      <mesh
        geometry={nodes.Object_90.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_91.geometry} material={materials.Madeira} />
      <mesh
        geometry={nodes.Object_93.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Madeira} />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_98.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_104.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_106.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_108.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_110.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_115.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_117.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_119.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_121.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_123.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_125.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_127.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_39.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_45.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_53.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_57.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_69.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_73.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_75.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_77.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_112.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_113.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.Grama_Light}
      />
      <mesh geometry={nodes.Object_129.geometry} material={materials.Madeira} />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Madeira} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Fundo} />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Vidro} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Concreto} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Pano} />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.Concreto_Dark}
      />
      <mesh
        geometry={nodes.Object_27.geometry}
        material={materials.Pano_Light}
      />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Madeira} />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Vidro} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Fundo} />
      <group
        position={[19.385, 10.065, -13.923]}
        rotation={[0.369, 0.825, -0.163]}
      >
        <mesh
          geometry={nodes.Object_0.geometry}
          material={materials.Pano_Light}
        />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials.Pano} />
        <mesh geometry={nodes.Object_0_2.geometry} material={materials.Fundo} />
      </group>
      <mesh geometry={nodes.Object_10.geometry} material={materials.Pano} />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Madeira} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Fundo} />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_100.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_81.geometry} material={materials.Madeira} />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        geometry={nodes.Object_102.geometry}
        material={materials.Concreto_Dark}
      />
      <mesh
        geometry={nodes.Object_79.geometry}
        material={materials.Concreto_Dark}
      />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Concreto} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Madeira} />
      <mesh
        geometry={nodes.Object_35.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Fundo} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.Grama} />
      <mesh geometry={nodes.Object_133.geometry} material={materials.Areia} />
      <group position={[-21.845, 2.488, 26.777]} scale={4}>
        <group rotation={[0, -0.151, 0]}>
          <group
            position={[4.391, -0.622, -7.44]}
            rotation={[0, -0.673, 0]}
            scale={1.8}
          >
            <mesh
              geometry={nodes.position_1.geometry}
              material={materials["00"]}
            />
            <mesh
              geometry={nodes.position_2.geometry}
              material={materials["01"]}
            />
            <mesh
              geometry={nodes.position_3.geometry}
              material={materials["02"]}
            />
            <mesh
              geometry={nodes.position_4.geometry}
              material={materials["03"]}
            />
            <mesh
              geometry={nodes.position_5.geometry}
              material={materials["04"]}
            />
            <mesh
              geometry={nodes.position_6.geometry}
              material={materials["05"]}
            />
            <mesh
              geometry={nodes.position_7.geometry}
              material={materials["06"]}
            />
            <mesh
              geometry={nodes.position_8.geometry}
              material={materials["07"]}
            />
            <mesh
              geometry={nodes.position_9.geometry}
              material={materials["08"]}
            />
            <mesh
              geometry={nodes.position_10.geometry}
              material={materials["09"]}
            />
            <mesh
              geometry={nodes.position_11.geometry}
              material={materials["11"]}
            />
            <mesh
              geometry={nodes.position_12.geometry}
              material={materials["10"]}
            />
          </group>
        </group>
      </group>
      <group
        position={[32.645, 1.877, 23.302]}
        rotation={[0, 1.571, 0]}
        scale={0.057}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials["Scene_-_Root"]}
            position={[409.104, -573.138, 32.951]}
            scale={1.5}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Rocket.geometry}
        material={materials["Material.005"]}
        rotation={[-0.578, -0.055, 0.183]}
        scale={0.35}
      />
      <group
        position={[6.117, 0.524, 36.948]}
        rotation={[0.182, -0.357, -0.114]}
      >
        <group position={[-3.5, -1.4, -1.12]}>
          <group
            position={[-13.957, -7.866, -30.696]}
            rotation={[-0.032, 0.42, 0.149]}
            scale={0.7}
          >
            <mesh
              geometry={nodes.Object_0004.geometry}
              material={materials.sine}
            />
            <mesh
              geometry={nodes.Object_0004_1.geometry}
              material={materials.cosine}
            />
            <mesh
              geometry={nodes.Object_0004_2.geometry}
              material={materials.cosineax}
            />
            <mesh
              geometry={nodes.Object_0004_3.geometry}
              material={materials.sineax}
            />
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.Object_131002.geometry}
        material={materials["Terra.001"]}
      />
      <mesh
        geometry={nodes.Object_131008.geometry}
        material={materials["Terra.001"]}
      />
      <mesh
        geometry={nodes.Object_131009.geometry}
        material={materials["Terra.001"]}
      />
      <group position={[18.411, 1.671, 11.899]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-24.187, -0.367, -4.41]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[5.776, 2.739, -12.266]}>
              <mesh
                geometry={nodes.Object_81669.geometry}
                material={materials["Terra.017"]}
              />
              <mesh
                geometry={nodes.Object_81669_1.geometry}
                material={materials["Terra.018"]}
              />
              <mesh
                geometry={nodes.Object_81669_2.geometry}
                material={materials["Grama.010"]}
              />
            </group>
          </group>
        </group>
      </group>
      <group position={[-6.639, 1.996, 8.804]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-24.187, -0.367, -4.41]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[30.826, 2.414, -9.17]}>
              <mesh
                geometry={nodes.Object_81670.geometry}
                material={materials["Terra.019"]}
              />
              <mesh
                geometry={nodes.Object_81670_1.geometry}
                material={materials["Terra.020"]}
              />
              <mesh
                geometry={nodes.Object_81670_2.geometry}
                material={materials["Grama.011"]}
              />
            </group>
          </group>
        </group>
      </group>
      <group position={[35.538, 1.996, -0.502]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-24.187, -0.367, -4.41]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[-13.244, 0.52, 0.136]}>
              <mesh
                geometry={nodes.Object_81672.geometry}
                material={materials["Terra.023"]}
              />
              <mesh
                geometry={nodes.Object_81672_1.geometry}
                material={materials["Terra.024"]}
              />
              <mesh
                geometry={nodes.Object_81672_2.geometry}
                material={materials["Grama.013"]}
              />
            </group>
          </group>
        </group>
      </group>
      <group
        position={[-12.188, 1.996, -34.056]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group position={[-24.187, -0.367, -4.41]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[37.075, 3.196, 33.689]}>
              <mesh
                geometry={nodes.Object_81673.geometry}
                material={materials["Terra.025"]}
              />
              <mesh
                geometry={nodes.Object_81673_1.geometry}
                material={materials["Terra.026"]}
              />
              <mesh
                geometry={nodes.Object_81673_2.geometry}
                material={materials["Grama.014"]}
              />
            </group>
          </group>
        </group>
      </group>
      <group
        position={[15.901, 1.996, -44.045]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group position={[-24.187, -0.367, -4.41]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[8.286, 2.414, 43.678]}>
              <mesh
                geometry={nodes.Object_81674.geometry}
                material={materials["Terra.027"]}
              />
              <mesh
                geometry={nodes.Object_81674_1.geometry}
                material={materials["Terra.028"]}
              />
              <mesh
                geometry={nodes.Object_81674_2.geometry}
                material={materials["Grama.015"]}
              />
            </group>
          </group>
        </group>
      </group>
      <group position={[0.62, -3.331, -2.493]}>
        <mesh
          geometry={nodes.Object_81675.geometry}
          material={materials["Terra.029"]}
        />
        <mesh
          geometry={nodes.Object_81675_1.geometry}
          material={materials["Terra.030"]}
        />
        <mesh
          geometry={nodes.Object_81675_2.geometry}
          material={materials["Grama.016"]}
        />
      </group>
      <group
        position={[15.641, -1.947, -1.083]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_47001.geometry}
            material={materials["Grama_Light.001"]}
            position={[-15.641, 1.947, 1.083]}
          />
        </group>
      </group>
      <group position={[21.608, 0.049, 10.573]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_51001.geometry}
            material={materials["Madeira_Dark.001"]}
            position={[-21.608, -0.049, -10.573]}
          />
        </group>
      </group>
      <group position={[21.656, 0.225, 10.001]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_50001.geometry}
            material={materials["Grama_Light.002"]}
            position={[-21.656, -0.225, -10.001]}
          />
        </group>
      </group>
      <group position={[4.467, -3.491, 28.109]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_15001.geometry}
            material={materials["Madeira_Dark.002"]}
            position={[-4.467, 3.491, -28.109]}
          />
        </group>
      </group>
      <group position={[6.4, 0.173, 15.963]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_102001.geometry}
            material={materials["Concreto_Dark.001"]}
            position={[-6.4, -0.173, -15.963]}
          />
        </group>
      </group>
      <group position={[4.457, -3.458, 28.118]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_13001.geometry}
            material={materials["Madeira.003"]}
            position={[-4.457, 3.458, -28.118]}
          />
        </group>
      </group>
      <group
        position={[-14.002, -1.448, 31.009]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_18001.geometry}
            material={materials["Grama_Light.004"]}
            position={[14.002, 1.448, -31.009]}
          />
          <mesh
            geometry={nodes.Object_19001.geometry}
            material={materials["Madeira_Dark.005"]}
            position={[14.002, 1.448, -31.009]}
          />
        </group>
      </group>
      <group
        position={[-1.035, -3.539, -22.572]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_62001.geometry}
            material={materials["Madeira_Dark.007"]}
            position={[1.035, 3.539, 22.572]}
          />
          <mesh
            geometry={nodes.Object_66001.geometry}
            material={materials["Madeira_Dark.007"]}
          />
          <mesh
            geometry={nodes.Object_64001.geometry}
            material={materials["Madeira_Dark.007"]}
            position={[1.035, 3.539, 22.572]}
          />
        </group>
      </group>
      <group
        position={[-5.051, 0.012, -35.183]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_100002.geometry}
            material={materials["Madeira_Dark.008"]}
            position={[5.051, -0.012, 35.183]}
          />
        </group>
      </group>
      <group
        position={[-19.02, -0.798, -5.699]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_129001.geometry}
            material={materials["Madeira.004"]}
            position={[19.02, 0.798, 5.699]}
          />
        </group>
      </group>
      <group
        position={[10.188, -0.189, -3.995]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_21001.geometry}
            material={materials["Madeira_Dark.010"]}
            position={[-10.188, 0.189, 3.995]}
          />
          <mesh
            geometry={nodes.Object_22001.geometry}
            material={materials["Grama_Light.006"]}
            position={[-10.188, 0.189, 3.995]}
          />
        </group>
      </group>
      <group position={[8.851, 2.929, -9.656]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_104001.geometry}
            material={materials["Grama_Light.007"]}
            position={[-8.851, -2.929, 9.656]}
          />
        </group>
      </group>
      <group position={[8.851, 2.929, -9.656]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_104002.geometry}
          material={materials["Grama_Light.009"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[2.002, 2.929, -15.268]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_104003.geometry}
            material={materials["Grama_Light.010"]}
            position={[-2.002, -2.929, 15.268]}
          />
        </group>
      </group>
      <group
        position={[-4.736, 2.929, -11.026]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_104005.geometry}
            material={materials["Grama_Light.012"]}
            position={[4.736, -2.929, 11.026]}
          />
        </group>
      </group>
      <group
        position={[-4.847, 2.929, -17.566]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_104006.geometry}
            material={materials["Grama_Light.013"]}
            position={[4.847, -2.929, 17.566]}
          />
        </group>
      </group>
      <group position={[4.941, 2.929, -5.834]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_104007.geometry}
            material={materials["Grama_Light.014"]}
            position={[-4.941, -2.929, 5.834]}
          />
        </group>
      </group>
      <group
        position={[-4.063, 3.278, -12.693]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_106001.geometry}
            material={materials["Grama_Light.015"]}
            position={[4.063, -3.278, 12.693]}
          />
        </group>
      </group>
      <group
        position={[-2.631, 3.278, -14.729]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_106002.geometry}
            material={materials["Grama_Light.016"]}
            position={[2.631, -3.278, 14.729]}
          />
        </group>
      </group>
      <group
        position={[-3.267, 3.278, -19.342]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_106003.geometry}
            material={materials["Grama_Light.017"]}
            position={[3.267, -3.278, 19.342]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Object_106005.geometry}
        material={materials["Grama_Light.019"]}
        position={[-6.373, -3.278, 27.551]}
      />
      <group position={[19.738, 0, -4.085]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_21002.geometry}
            material={materials["Madeira_Dark.011"]}
            position={[-19.737, -0.777, 4.026]}
          />
          <mesh
            geometry={nodes.Object_22002.geometry}
            material={materials["Grama_Light.020"]}
            position={[-19.737, -0.777, 4.026]}
          />
        </group>
      </group>
      <group
        position={[24.072, -3.348, 18.573]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_21003.geometry}
            material={materials["Madeira_Dark.012"]}
            position={[-24.072, 3.348, -18.573]}
          />
          <mesh
            geometry={nodes.Object_22003.geometry}
            material={materials["Grama_Light.021"]}
            position={[-24.072, 3.348, -18.573]}
          />
        </group>
      </group>
      <group position={[7.178, -0.135, 12.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_47002.geometry}
            material={materials["Grama_Light.022"]}
            position={[-7.178, 0.135, -12.9]}
          />
          <mesh
            geometry={nodes.Object_48001.geometry}
            material={materials["Madeira_Dark.013"]}
            position={[-7.178, 0.135, -12.9]}
          />
        </group>
      </group>
      <group position={[5.596, -0.269, 15.737]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_44001.geometry}
            material={materials["Madeira_Dark.014"]}
            position={[-5.596, 0.269, -15.737]}
          />
          <mesh
            geometry={nodes.Object_45001.geometry}
            material={materials["Grama_Light.023"]}
            position={[-5.596, 0.269, -15.737]}
          />
        </group>
      </group>
      <group
        position={[-20.389, -0.354, -9.219]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_53002.geometry}
            material={materials["Madeira_Dark.015"]}
            position={[20.389, 0.354, 9.219]}
          />
          <mesh
            geometry={nodes.Object_54002.geometry}
            material={materials["Grama_Light.024"]}
            position={[20.389, 0.354, 9.219]}
          />
        </group>
      </group>
      <group
        position={[-0.296, -3.198, -17.989]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_53003.geometry}
            material={materials["Madeira_Dark.016"]}
            position={[0.296, 3.198, 17.989]}
          />
          <mesh
            geometry={nodes.Object_54003.geometry}
            material={materials["Grama_Light.025"]}
            position={[0.296, 3.198, 17.989]}
          />
        </group>
      </group>
      <group
        position={[-0.195, -3.552, -27.202]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_64002.geometry}
            material={materials["Madeira_Dark.017"]}
            position={[0.195, 3.552, 27.202]}
          />
        </group>
      </group>
      <group position={[-12.492, 0.03, -0.19]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_28001.geometry}
            material={materials["Madeira.007"]}
            position={[12.492, -0.03, 0.19]}
          />
        </group>
      </group>
      <group
        position={[-11.985, -0.021, 0.061]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_29001.geometry}
            material={materials["Madeira_Dark.018"]}
            position={[11.985, 0.021, -0.061]}
          />
        </group>
      </group>
      <group
        position={[-15.926, 2.008, 17.158]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_44002.geometry}
            material={materials["Madeira_Dark.019"]}
            position={[15.926, -2.008, -17.158]}
          />
          <mesh
            geometry={nodes.Object_45002.geometry}
            material={materials["Grama_Light.026"]}
            position={[15.926, -2.008, -17.158]}
          />
        </group>
      </group>
      <group
        position={[-15.926, 2.008, 17.158]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_44003.geometry}
            material={materials["Madeira_Dark.020"]}
            position={[15.926, -2.008, -17.158]}
          />
          <mesh
            geometry={nodes.Object_45003.geometry}
            material={materials["Grama_Light.027"]}
            position={[15.926, -2.008, -17.158]}
          />
        </group>
      </group>
      <group
        position={[-15.961, -0.837, -0.492]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_129003.geometry}
            material={materials["Madeira.008"]}
            position={[15.961, 0.837, 0.492]}
          />
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group
          position={[-9.115, 10.89, -17.942]}
          rotation={[1.541, 0.96, -2.157]}
        >
          <mesh
            geometry={nodes.Object_0001.geometry}
            material={materials["Pano_Light.001"]}
          />
          <mesh
            geometry={nodes.Object_0001_1.geometry}
            material={materials["Pano.001"]}
          />
          <mesh
            geometry={nodes.Object_0001_2.geometry}
            material={materials["Fundo.001"]}
          />
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group
          position={[19.385, 10.065, -13.923]}
          rotation={[1.732, 0.384, -2.285]}
        >
          <mesh
            geometry={nodes.Object_0002.geometry}
            material={materials["Pano_Light.002"]}
          />
          <mesh
            geometry={nodes.Object_0002_1.geometry}
            material={materials["Pano.002"]}
          />
          <mesh
            geometry={nodes.Object_0002_2.geometry}
            material={materials["Fundo.002"]}
          />
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group
          position={[-15.155, 13.194, -24.904]}
          rotation={[1.304, 0.401, -2.435]}
        >
          <mesh
            geometry={nodes.Object_0003.geometry}
            material={materials["Pano_Light.003"]}
          />
          <mesh
            geometry={nodes.Object_0003_1.geometry}
            material={materials["Pano.003"]}
          />
          <mesh
            geometry={nodes.Object_0003_2.geometry}
            material={materials["Fundo.003"]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Object_33001.geometry}
        material={materials["Concreto.001"]}
        position={[-14.969, 2.773, -23.489]}
      />
      <mesh
        geometry={nodes.Object_33003.geometry}
        material={materials["Concreto.003"]}
        position={[16.757, 2.6, -34.347]}
      />
      <mesh
        geometry={nodes.Object_34002.geometry}
        material={materials["Madeira.002"]}
        position={[16.509, 2.551, -34.717]}
      />
    </a.group>
  );
};

export default Island;
