global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-data-service'
    static_configs:
      - targets: ['user-data-service:8081']
    metrics_path: '/user/metrics'

  - job_name: 'feed-data-service'
    static_configs:
      - targets: ['feed-data-service:8080']
    metrics_path: '/feed/metrics'

  - job_name: 'evaluation-service'
    static_configs:
      - targets: ['evaluation-service:8080']
    metrics_path: '/evaluation/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 