apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-role-binding
subjects:
  - kind: ServiceAccount
    name: portainer-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: portainer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  labels:
    app: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      serviceAccountName: portainer-sa
      containers:
        - name: portainer
          image: portainer/portainer-ce:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: PORTAINER_EDGE
              value: "0"
            - name: PORTAINER_EDGE_ASYNC
              value: "0"
            - name: PORTAINER_EDGE_INSECURE_POLL
              value: "0"
            - name: PORTAINER_EDGE_INACTIVITY_TIMEOUT
              value: "5m"
            - name: PORTAINER_EDGE_POLLING_INTERVAL
              value: "5s"
            - name: PORTAINER_BASE_URL
              value: "/portainer"
            - name: PORTAINER_SERVE_FROM_SUBPATH
              value: "true"
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: portainer-service
  labels:
    app: portainer
spec:
  selector:
    app: portainer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-ingress
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/protocols: "http,https"
    konghq.com/preserve-host: "true"
    konghq.com/connect-timeout: "60000"
    konghq.com/read-timeout: "60000"
    konghq.com/write-timeout: "60000"
    konghq.com/retries: "5"
    konghq.com/rewrite: "/portainer"
    konghq.com/healthchecks.active.type: "http"
    konghq.com/healthchecks.active.http_path: "/portainer/api/status"
    konghq.com/healthchecks.active.timeout: "5"
    konghq.com/healthchecks.active.concurrency: "10"
    konghq.com/healthchecks.active.interval: "10"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /portainer
            pathType: Prefix
            backend:
              service:
                name: portainer-service
                port:
                  number: 9000
