FROM golang:1.24-alpine

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the script
RUN go build -o init-badges ./scripts/init_badges.go

# Run the script
CMD ["./init-badges"] 