apiVersion: v1
kind: Service
metadata:
  name: mongo-user-data-service
spec:
  selector:
    app: mongo-user-data-service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
