apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-user-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-user-data-service
  template:
    metadata:
      labels:
        app: mongo-user-data-service
    spec:
      containers:
        - name: mongo-user-data-service
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: mongo-user-data-storage
              mountPath: /data/db
      volumes:
        - name: mongo-user-data-storage
          persistentVolumeClaim:
            claimName: mongo-user-data-service-pvc
