apiVersion: apps/v1
kind: Deployment
metadata:
  name: formulas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formulas-service
  template:
    metadata:
      labels:
        app: formulas-service
    spec:
      containers:
        - name: formulas-service
          image: formulas-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
