name: Go CI – All Services

on:
  push:
    paths:
      - "backend/**.go"
      - "backend/**/go.mod"
      - ".github/workflows/go-ci.yml"
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - backend/evaluation-service
          - backend/feed-data-service
          - backend/user-data-service

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Verify & tidy modules
        run: |
          go vet ./...
          go mod tidy

      - name: Build binary
        run: go build -v ./...
