name: Go CI – All Services

on:
  push:
    paths:
      - "backend/**.go"
      - "backend/**/go.mod"
      - "backend/**/Dockerfile"
      - "backend/**/k8s/*.yaml"
      - ".github/workflows/go-ci.yml"
  pull_request:

jobs:
  build-test:
    runs-on: self-hosted

    strategy:
      matrix:
        service:
          - backend/evaluation-service
          - backend/feed-data-service
          - backend/user-data-service

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        run: |
          echo "Setting up kubectl configuration..."
          docker ps | findstr "kindest/node"
          
          $env:KUBECONFIG="$HOME\.kube\config"
          echo "KUBECONFIG set to: $env:KUBECONFIG"
          
          kubectl config use-context kind-visioscience
          echo "Using context: kind-visioscience"

      - name: Verify kubectl access
        run: |
          echo "Verifying kubectl access..."
          kubectl config view
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods
          echo "Kubectl access verified successfully"

      - name: Check for existing Go installation
        id: check_go
        run: |
          if (Get-Command go -ErrorAction SilentlyContinue) {
            $goVersion = (go version).Split(" ")[2]
            echo "Found existing Go installation: $goVersion"
            echo "GO_VERSION=$goVersion" >> $env:GITHUB_ENV
            echo "GO_EXISTS=true" >> $env:GITHUB_ENV
          } else {
            echo "No existing Go installation found"
            echo "GO_EXISTS=false" >> $env:GITHUB_ENV
          }

      - name: Set up Go
        if: env.GO_EXISTS == 'false'
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true
          check-latest: true

      - name: Verify & tidy modules
        run: |
          go vet ./...
          go mod tidy

      - name: Build binary
        run: go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract service name
        id: extract
        run: |
          $SERVICE_NAME = "${{ matrix.service }}".Replace('backend/', '')
          # Remove -service suffix for feed-data and user-data
          if ($SERVICE_NAME -eq 'feed-data-service' -or $SERVICE_NAME -eq 'user-data-service') {
              $SERVICE_NAME = $SERVICE_NAME.Replace('-service', '')
          }
          echo "name=$SERVICE_NAME" >> $env:GITHUB_OUTPUT
          echo "Processing service: $SERVICE_NAME"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          push: true
          tags: dragomir1401/${{ steps.extract.outputs.name }}:latest

      - name: Deploy to Kubernetes
        run: |
          echo "Starting deployment for ${{ steps.extract.outputs.name }}..."
          if (Test-Path -Path "k8s" -PathType Container) {
            echo "Found k8s configuration, applying..."
            kubectl apply -f k8s/
            
            echo "Waiting for deployment to complete..."
            kubectl rollout status deployment/${{ steps.extract.outputs.name }} -n default
            
            echo "Deployment completed successfully for ${{ steps.extract.outputs.name }}"
          } else {
            echo "No k8s configuration found for ${{ steps.extract.outputs.name }}"
          }